### ISSUE TITLE
Embed the lifecycle scripts in the releases or checksum to prevent tampering

### ISSUE THREAD

**Issue by mensfeld** [second-state/wasmedge-core#9]
Hey,

My name is Maciej Mensfeld and I run a research security project called WhiteSource Diffend.io.

I've noticed, that this ` wasmedge-core` downloads lifecycle scripts uses them (ref https://github.com/second-state/wasmedge-core/commit/b82ebf3f215b5b81ae4556f3164e1d45631f2cda). While it's a totally common pattern, what is lacking here is integrity verification and version pinning.

You could verify the integrity of the downloaded files before using it by comparing the file hash to a hardcoded, expected file hash.

This is essentially what package managers do to verify the integrity of downloaded packages.

Doing this would prevent attack scenarios in which `WasmEdge/WasmEdge` Github scripts are compromised or manipulated in a malicious way.

Have a great day :)

**Comment by hydai** [comment]
@dm4 Our installation script will be finalized at 0.9.0 official release. So I think it's time to change the `master` to a specific commit hash for our 0.9.0 wasmedge-core release. Also, wasmedge-extension should be updated.

**Comment by hydai** [comment]
Thanks @mensfeld 
We used the 0.9.0 release version with sha1sum checksum to make sure the pinning version :-)

**Comment by mensfeld** [comment]
Great. Thank you :pray:
